### ISSUE TITLE
[REFACTOR] docker compose 파일 생성

### ISSUE THREAD

**Issue by Minjoo522** [zolling-paper/backend#42]
### 📌 리팩터링할 부분

docker compose 파일을 생성해 배포시 workflow 명령어의 복잡도를 줄이고 유지보수성을 높입니다.

### 🥲 as-is

```yml
    steps:
      - name: 🚀 Deployment
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker stop ${{ secrets.DOCKER_CONTAINER_NAME }} | true
          docker rm ${{ secrets.DOCKER_CONTAINER_NAME }} | true
          docker image prune -a -f
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME_DEV }}:${{ github.sha }}
          docker run --name ${{ secrets.DOCKER_CONTAINER_NAME }} -d -v /logs:/logs -p 8080:8080 \
          -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
          -e EXPIRE_TIME=${{ secrets.EXPIRE_TIME }} \
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME_DEV }}:${{ github.sha }}
```

### 😍 to-be

```yml
      - name: Docker Compose up
        run: docker compose -f compose.yml up -d

      - name: Clean Unused Image
        run: docker image prune -af
```
